#include "emitter.hpp"

void emit_typst(std::ostream& out, const Document& doc, const std::string& code_lang) {
    out << "// Generated by noweb-typst\n\n";
    out << "#set heading(numbering: \"1.1\")\n\n";
    out << "#let today = datetime.today()\n\n";
    out << "#set page(header: [ #set text(8pt); #today.display(\"[month repr:long] [day], [year]\") #h(1fr) ])\n\n";




    for (const auto& block : doc.blocks) {
        // Code block
        if (block.kind == Block::Kind::Code) {
            out << "$chevron.l$";
            if (block.text.empty())
                out << "Unnamed chunk";
            else
                out << block.name;
            out << "$chevron.r#h(-0.1em)eq.triple$\n\n";
            out << "```" << code_lang << "\n";
            out << block.text;
            if (block.text.empty() || block.text.back() != '\n')
                out << '\n';

            out << "```\n\n";
        // Doc block
        } else {
            out << block.text << "\n";
        }
    }
}
